In [1]:
import numpy as np

In [148]:
x=np.array([5,2,9,4])
y=np.array([10,9,4,3])
z=np.array([2.5,9.7,1.2,2.4])
num=np.array([-1.6,-2.9,-3.0,-8.9])
angles=np.array([90,180,270,360])
set=np.array([2,2,2,3,4,3,9,9,8,7,7])

In [22]:
sqrt=np.sqrt(x)
power=np.power(x,3)
mean=np.mean(x)
exp=np.exp(x)
log=np.log(x)
log2=np.log2(x)
log10=np.log10(x)
a=np.reciprocal(x)
b=np.isreal(x)
c=np.square(x)

In [26]:
sqrt,power,mean,exp,log,log2,log10,a,b,c


(array([2.23606798, 1.41421356, 3.        , 2.        ]),
 array([125,   8, 729,  64], dtype=int32),
 5.0,
 array([1.48413159e+02, 7.38905610e+00, 8.10308393e+03, 5.45981500e+01]),
 array([1.60943791, 0.69314718, 2.19722458, 1.38629436]),
 array([2.32192809, 1.        , 3.169925  , 2.        ]),
 array([0.69897   , 0.30103   , 0.95424251, 0.60205999]),
 array([0.4       , 0.10309278, 0.83333333, 0.41666667]),
 array([ True,  True,  True,  True]),
 array([25,  4, 81, 16], dtype=int32))

In [27]:
x,y,z

(array([5, 2, 9, 4]), array([10,  9,  4,  3]), array([2.5, 9.7, 1.2, 2.4]))

In [54]:
absolute=np.absolute(num)
d=np.maximum(x,y)
f=np.minimum(x,y)

In [55]:
absolute,d,f

(array([1.6, 2.9, 3. , 8.9]), array([10,  9,  9,  4]), array([5, 2, 4, 3]))

In [108]:
sinit=np.sin(angles)
sinit

array([ 0.89399666, -0.80115264, -0.17604595,  0.95891572])

In [57]:
np.cos(angles)

array([-0.44807362, -0.59846007,  0.98438195, -0.28369109])

In [58]:
np.tan(angles)

array([-1.99520041,  1.33869021, -0.17883906, -3.38014041])

In [171]:
sumit=np.sum(x)
add=np.add(x,y)
mul=np.multiply(x,y)
division=np.divide(x,y)
diff=np.subtract(x,y)
tru=np.trunc(z)
fixit=np.fix(num)
roundnum=np.around(sinit,2)
flornum=np.floor(sinit)
ceil=np.ceil(num)
modit=np.mod(x,y)
divnmod=np.divmod(x,y)
cumsum=np.cumsum(x)

In [172]:
sumit,add,mul,division,diff,tru,fixit,roundnum,flornum,ceil,modit,divnmod,cumsum

(20,
 array([15, 11, 13,  7]),
 array([50, 18, 36, 12]),
 array([0.5       , 0.22222222, 2.25      , 1.33333333]),
 array([-5, -7,  5,  1]),
 array([2., 9., 1., 2.]),
 array([-1., -2., -3., -8.]),
 array([ 0.89, -0.8 , -0.18,  0.96]),
 array([ 0., -1., -1.,  0.]),
 array([-1., -2., -3., -8.]),
 array([5, 2, 1, 1], dtype=int32),
 (array([0, 0, 2, 1], dtype=int32), array([5, 2, 1, 1], dtype=int32)),
 array([ 5,  7, 16, 20], dtype=int32))

In [138]:
num1=20
num2=30
lcm=np.lcm(num1,num2)
gcd=np.gcd(num1,num2)
lcm,gcd

(60, 10)

In [136]:
lcmit=np.lcm.reduce(x)
gcdit=np.gcd.reduce(x)

In [137]:
lcmit,gcdit

(180, 1)

In [145]:
d2r=np.deg2rad(angles)
r2d=np.rad2deg(d2r)

In [146]:
d2r,r2d

(array([1.57079633, 3.14159265, 4.71238898, 6.28318531]),
 array([ 90., 180., 270., 360.]))

In [161]:
u=np.unique(set)
union=np.union1d(set,u)
intersection=np.intersect1d(set,x)

In [158]:
u,union,intersection

(array([2, 3, 4, 7, 8, 9]), array([2, 3, 4, 7, 8, 9]), array([2, 4, 9]))

In [176]:
dif=np.diff(x)
diff=np.diff(x,n=2)
where=np.where(u>5,"ok","nok")

In [177]:
dif,diff,where

(array([-3,  7, -5]),
 array([ 10, -12]),
 array(['nok', 'nok', 'nok', 'ok', 'ok', 'ok'], dtype='<U3'))

In [183]:
matrix1=np.random.randn(2,3)
matrix2=np.random.randn(3,2)

In [184]:
matrix1,matrix2

(array([[-0.87084469,  0.05772106, -2.24105522],
        [ 0.2118347 ,  0.9979031 , -0.4424553 ]]),
 array([[ 1.91608955,  2.05759293],
        [-0.45773642,  1.52764334],
        [ 0.16232218, -1.04896083]]))

In [192]:
dot=matrix1.dot(matrix2)
tp=matrix1.transpose()
plus=matrix1+matrix1
minus=matrix2-matrix2

In [195]:
dot,tp,plus,minus,matrix1.trace()

(array([[-2.05881042,  0.64711244],
        [-0.12270265,  2.42442788]]),
 array([[-0.87084469,  0.2118347 ],
        [ 0.05772106,  0.9979031 ],
        [-2.24105522, -0.4424553 ]]),
 array([[-1.74168939,  0.11544211, -4.48211045],
        [ 0.4236694 ,  1.9958062 , -0.88491059]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 0.12705840483060615)

In [197]:
base=2
perp=3
np.hypot(base,perp)


3.605551275463989

In [198]:
np.arcsin(1)

1.5707963267948966

In [199]:
np.arccos(1)

0.0

In [200]:
np.arctan(1)

0.7853981633974483