In [2]:
import numpy as np

In [69]:
#Q1
arr=np.random.randint(10,51,10)
arr2d=arr.reshape((2,5))
arr2d

array([[25, 38, 15, 38, 50],
       [21, 49, 41, 47, 43]])

In [32]:
#Q2
arr=np.random.randint(10,51,10)
arr2d2=arr.reshape((2,5))
arr2d2
np.vstack((arr2d,arr2d2))

array([[40, 39, 16, 15, 38],
       [29, 31, 23, 25, 48],
       [46, 15, 34, 48, 19],
       [24, 17, 33, 16, 26]])

In [33]:
#Q3
np.hstack((arr2d,arr2d2))

array([[40, 39, 16, 15, 38, 46, 15, 34, 48, 19],
       [29, 31, 23, 25, 48, 24, 17, 33, 16, 26]])

In [35]:
#Q4
arr1d=arr2d.reshape(10)
arr1d

array([40, 39, 16, 15, 38, 29, 31, 23, 25, 48])

In [53]:
#Q5
arr=np.random.randint(10,51,12)
newarr2d=arr.reshape((3,2,2))
new1d=newarr2d.reshape(12)
newarr2d,new1d

(array([[[42, 23],
         [36, 27]],
 
        [[29, 48],
         [35, 15]],
 
        [[38, 19],
         [35, 19]]]),
 array([42, 23, 36, 27, 29, 48, 35, 15, 38, 19, 35, 19]))

In [54]:
#Q6
new1d.reshape((3,2,2))

array([[[42, 23],
        [36, 27]],

       [[29, 48],
        [35, 15]],

       [[38, 19],
        [35, 19]]])

In [60]:
#Q7
array=np.random.randint(10,51,25)
arr5=array.reshape((5,5))
fbf=arr5
sqr=fbf**2
fbf,sqr


(array([[49, 46, 38, 20, 29],
        [46, 34, 12, 23, 39],
        [12, 42, 28, 22, 31],
        [39, 39, 40, 22, 43],
        [14, 26, 19, 39, 28]]),
 array([[2401, 2116, 1444,  400,  841],
        [2116, 1156,  144,  529, 1521],
        [ 144, 1764,  784,  484,  961],
        [1521, 1521, 1600,  484, 1849],
        [ 196,  676,  361, 1521,  784]], dtype=int32))

In [80]:
#Q8
arr=np.random.randint(5,41,30)
fb6=arr.reshape(5,6)
mean=np.mean(fb6)
fb6,mean

(array([[17, 16, 32, 27, 35, 26],
        [23, 16, 21, 19, 39, 31],
        [15, 20, 39, 37,  5, 27],
        [39, 20,  9, 27, 21, 38],
        [40, 34,  7, 28, 23, 19]]),
 25.0)

In [81]:
#Q9
np.std(fb6)

9.80136044978791

In [83]:
#Q10
np.median(fb6)

24.5

In [85]:
#Q11
np.transpose(fb6)

array([[17, 23, 15, 39, 40],
       [16, 16, 20, 20, 34],
       [32, 21, 39,  9,  7],
       [27, 19, 37, 27, 28],
       [35, 39,  5, 21, 23],
       [26, 31, 27, 38, 19]])

In [122]:
#Q12
fbf=np.random.randint(1,30,16).reshape(4,4)
fbf.trace()

36

In [123]:
#Q13
np.linalg.det(fbf)

16002.000000000013

In [149]:
 #Q14
arr=np.arange(11)
perc5=np.percentile(arr,5)
perc95=np.percentile(arr,95)
perc5,perc95

(0.5, 9.5)